#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#user controller routes
user:
   path: /user
   controller: App\Controller\UserController::index

registro:
   path: /registro
   controller: App\Controller\UserController::registro
   methods: [POST]  

login:
   path: /login
   controller: App\Controller\UserController::login
   methods: [POST] 

editar:
   path: /editar
   controller: App\Controller\UserController::editar
   methods: [PUT]  

#wallet controller routes
whallet:
   path: /whallet
   controller: App\Controller\WhalletController::index

recargar:
   path: /recargar
   controller: App\Controller\WhalletController::recargar

pagar:
   path: /pagar
   controller: App\Controller\WhalletController::pagar
   methods: [POST]