#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#user controller routes
user:
   path: /user
   controller: App\Controller\UserController::index


#wallet controller routes
whallet:
   path: /whallet
   controller: App\Controller\WhalletController::index